import {
  SvgAlertCircle,
  SvgAlertTriangle,
  SvgBarChart,
  SvgBell,
  SvgBlocks,
  SvgBracketCurly,
  SvgBranch,
  SvgCalendar,
  SvgClock,
  SvgColumn,
  SvgEdit,
  SvgFileBraces,
  SvgFileText,
  SvgFilter,
  SvgGlobe,
  SvgHardDrive,
  SvgHash,
  SvgLink,
  SvgListTree,
  SvgMail,
  SvgPlayCircle,
  SvgPlusCircle,
  SvgRefreshCw,
  SvgRevert,
  SvgSearchMenu,
  SvgSort,
  SvgSparkle,
  SvgSpreadsheetFile,
  SvgSquare,
  SvgStopCircle,
  SvgTag,
  SvgTextLines,
  SvgUploadCloud,
  SvgUserCheck,
  SvgWorkflow,
  SvgArrowExchange,
} from "@opal/icons";
import type { IconFunctionComponent } from "@opal/types";
import type { NodeGroup } from "@/lib/ton/automations";

const ICONS: Record<string, IconFunctionComponent> = {
  play: SvgPlayCircle,
  calendar: SvgCalendar,
  upload: SvgUploadCloud,
  alert: SvgAlertTriangle,
  tag: SvgTag,
  chart: SvgBarChart,
  warning: SvgAlertCircle,
  branch: SvgBranch,
  switch: SvgArrowExchange,
  repeat: SvgRefreshCw,
  refresh: SvgRevert,
  box: SvgSquare,
  columns: SvgColumn,
  clock: SvgClock,
  stop: SvgStopCircle,
  variable: SvgBracketCurly,
  plus: SvgPlusCircle,
  list: SvgListTree,
  database: SvgHardDrive,
  compose: SvgEdit,
  braces: SvgFileBraces,
  filter: SvgFilter,
  sort: SvgSort,
  layers: SvgBlocks,
  sigma: SvgHash,
  table: SvgSpreadsheetFile,
  link: SvgLink,
  sparkles: SvgSparkle,
  scan: SvgSearchMenu,
  text: SvgTextLines,
  bell: SvgBell,
  mail: SvgMail,
  globe: SvgGlobe,
  check: SvgUserCheck,
  file: SvgFileText,
};

export function nodeIcon(key: string | undefined): IconFunctionComponent {
  return (key && ICONS[key]) || SvgWorkflow;
}

export const GROUP_ORDER: NodeGroup[] = ["ton", "email", "ai", "data", "control", "variables", "approval", "integration"];
